# Generated by Django 3.2 on 2021-04-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Pos', 'Positive'), ('Neg', 'Negative'), ('Inv', 'Invalid')], default='Negative', max_length=8)),
            ],
        ),
    ]
